// Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wso2/cli/module/v1/contract.proto

// Package wso2.cli.module.v1 is version 1 of the WSO2 CLI module contract: the
// messages the shell and a product module exchange over the module process's
// inherited standard input and standard output.
//
// Each frame on the wire is an unsigned-varint byte length followed by one
// encoded Envelope. Module standard output carries these frames only; module
// standard error carries bounded diagnostics, and only the shell writes
// user-facing output. See docs/adr/0002-module-transport.md and
// docs/adr/0003-shell-owned-output.md.
//
// Compatibility rules for this package:
//
//   - unknown fields are preserved and ignored, so a field may be added within
//     this version;
//   - an unknown Envelope message kind fails closed rather than being skipped;
//     and
//   - a required capability the peer does not recognize fails closed.

package contractv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OutputMode is the rendering the shell will apply to a Result.
type OutputMode int32

const (
	OutputMode_OUTPUT_MODE_UNSPECIFIED OutputMode = 0
	// OUTPUT_MODE_TABLE renders a human-readable table.
	OutputMode_OUTPUT_MODE_TABLE OutputMode = 1
	// OUTPUT_MODE_JSON renders deterministic JSON.
	OutputMode_OUTPUT_MODE_JSON OutputMode = 2
)

// Enum value maps for OutputMode.
var (
	OutputMode_name = map[int32]string{
		0: "OUTPUT_MODE_UNSPECIFIED",
		1: "OUTPUT_MODE_TABLE",
		2: "OUTPUT_MODE_JSON",
	}
	OutputMode_value = map[string]int32{
		"OUTPUT_MODE_UNSPECIFIED": 0,
		"OUTPUT_MODE_TABLE":       1,
		"OUTPUT_MODE_JSON":        2,
	}
)

func (x OutputMode) Enum() *OutputMode {
	p := new(OutputMode)
	*p = x
	return p
}

func (x OutputMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputMode) Descriptor() protoreflect.EnumDescriptor {
	return file_wso2_cli_module_v1_contract_proto_enumTypes[0].Descriptor()
}

func (OutputMode) Type() protoreflect.EnumType {
	return &file_wso2_cli_module_v1_contract_proto_enumTypes[0]
}

func (x OutputMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputMode.Descriptor instead.
func (OutputMode) EnumDescriptor() ([]byte, []int) {
	return file_wso2_cli_module_v1_contract_proto_rawDescGZIP(), []int{0}
}

// Envelope wraps every message on the wire so framing, invocation binding, and
// message dispatch are uniform in both directions.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// invocation_id binds a message to one shell invocation. The shell mints it
	// and sends it first in Welcome; every message after the handshake must
	// repeat it, and a peer that omits or changes it is a protocol failure.
	//
	// Hello precedes the handshake, so it is the only message that leaves this
	// field empty.
	InvocationId string `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	// correlation_id pairs a response with its request for message kinds that
	// may be interleaved. A terminal message leaves it empty.
	CorrelationId string `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// message is the semantic payload. An envelope carrying no known payload
	// fails closed.
	//
	// Types that are valid to be assigned to Message:
	//
	//	*Envelope_Hello
	//	*Envelope_Welcome
	//	*Envelope_Invoke
	//	*Envelope_Result
	//	*Envelope_Problem
	Message       isEnvelope_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_wso2_cli_module_v1_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_wso2_cli_module_v1_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_wso2_cli_module_v1_contract_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *Envelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Envelope) GetMessage() isEnvelope_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Envelope) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Envelope) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *Envelope) GetInvoke() *Invoke {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Invoke); ok {
			return x.Invoke
		}
	}
	return nil
}

func (x *Envelope) GetResult() *Result {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *Envelope) GetProblem() *Problem {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Problem); ok {
			return x.Problem
		}
	}
	return nil
}

type isEnvelope_Message interface {
	isEnvelope_Message()
}

type Envelope_Hello struct {
	Hello *Hello `protobuf:"bytes,10,opt,name=hello,proto3,oneof"`
}

type Envelope_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,11,opt,name=welcome,proto3,oneof"`
}

type Envelope_Invoke struct {
	Invoke *Invoke `protobuf:"bytes,12,opt,name=invoke,proto3,oneof"`
}

type Envelope_Result struct {
	// Field numbers 13, 14, and 15 are held for the authentication broker
	// exchange (AcquireAccess, AccessGranted, AccessDenied), which is added by
	// a later slice increment.
	Result *Result `protobuf:"bytes,16,opt,name=result,proto3,oneof"`
}

type Envelope_Problem struct {
	Problem *Problem `protobuf:"bytes,17,opt,name=problem,proto3,oneof"`
}

func (*Envelope_Hello) isEnvelope_Message() {}

func (*Envelope_Welcome) isEnvelope_Message() {}

func (*Envelope_Invoke) isEnvelope_Message() {}

func (*Envelope_Result) isEnvelope_Message() {}

func (*Envelope_Problem) isEnvelope_Message() {}

// Hello is the first message a module sends. It states who is actually running
// so the shell can compare runtime identity with the module receipt it
// resolved.
type Hello struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Module *ModuleIdentity        `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	// protocol_versions are the module-contract versions this module can speak,
	// newest first. The shell selects one and reports it in Welcome.
	ProtocolVersions []uint32 `protobuf:"varint,2,rep,packed,name=protocol_versions,json=protocolVersions,proto3" json:"protocol_versions,omitempty"`
	// required_capabilities name optional protocol behaviour the module cannot
	// run without. A capability the shell does not recognize fails closed, so a
	// module can never silently lose a behaviour it depends on.
	RequiredCapabilities []string `protobuf:"bytes,3,rep,name=required_capabilities,json=requiredCapabilities,proto3" json:"required_capabilities,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_wso2_cli_module_v1_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_wso2_cli_module_v1_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_wso2_cli_module_v1_contract_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetModule() *ModuleIdentity {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *Hello) GetProtocolVersions() []uint32 {
	if x != nil {
		return x.ProtocolVersions
	}
	return nil
}

func (x *Hello) GetRequiredCapabilities() []string {
	if x != nil {
		return x.RequiredCapabilities
	}
	return nil
}

// ModuleIdentity is the identity of the executing module.
type ModuleIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// namespace is the single top-level command name this module owns.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// version is the module's own release version.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// sdk_version is the SDK release the module was built against.
	SdkVersion    string `protobuf:"bytes,3,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleIdentity) Reset() {
	*x = ModuleIdentity{}
	mi := &file_wso2_cli_module_v1_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleIdentity) ProtoMessage() {}

func (x *ModuleIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_wso2_cli_module_v1_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleIdentity.ProtoReflect.Descriptor instead.
func (*ModuleIdentity) Descriptor() ([]byte, []int) {
	return file_wso2_cli_module_v1_contract_proto_rawDescGZIP(), []int{2}
}

func (x *ModuleIdentity) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ModuleIdentity) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModuleIdentity) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

// Welcome answers Hello. It closes the handshake by fixing the protocol version
// and the invocation identity for everything that follows.
type Welcome struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// protocol_version is the single version both sides speak for this
	// invocation.
	ProtocolVersion uint32         `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Shell           *ShellIdentity `protobuf:"bytes,2,opt,name=shell,proto3" json:"shell,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_wso2_cli_module_v1_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_wso2_cli_module_v1_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_wso2_cli_module_v1_contract_proto_rawDescGZIP(), []int{3}
}

func (x *Welcome) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Welcome) GetShell() *ShellIdentity {
	if x != nil {
		return x.Shell
	}
	return nil
}

// ShellIdentity is the identity of the shell that launched the module. A module
// may report it in diagnostics but must not vary its result on it.
type ShellIdentity struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// platform is the "os/arch" pair the shell runs on.
	Platform      string `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellIdentity) Reset() {
	*x = ShellIdentity{}
	mi := &file_wso2_cli_module_v1_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellIdentity) ProtoMessage() {}

func (x *ShellIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_wso2_cli_module_v1_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellIdentity.ProtoReflect.Descriptor instead.
func (*ShellIdentity) Descriptor() ([]byte, []int) {
	return file_wso2_cli_module_v1_contract_proto_rawDescGZIP(), []int{4}
}

func (x *ShellIdentity) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ShellIdentity) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

// Invoke asks the module to run one product command. Exactly one Invoke is sent
// per invocation, and the module answers with exactly one terminal Result or
// Problem.
type Invoke struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// namespace repeats the namespace the shell resolved, so a module that owns
	// more than one build cannot act on a command routed to another module.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// command_path is the command within the namespace, without the namespace
	// itself. "wso2 reference status" arrives as ["status"].
	CommandPath []string `protobuf:"bytes,2,rep,name=command_path,json=commandPath,proto3" json:"command_path,omitempty"`
	// arguments are the remaining user arguments, unparsed by the shell.
	Arguments []string `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	// output_mode tells the module which rendering the shell will perform. It is
	// advisory: a module may use it to skip work whose only purpose is display.
	// It never permits a module to format or write user output itself.
	OutputMode OutputMode        `protobuf:"varint,4,opt,name=output_mode,json=outputMode,proto3,enum=wso2.cli.module.v1.OutputMode" json:"output_mode,omitempty"`
	Policy     *InvocationPolicy `protobuf:"bytes,5,opt,name=policy,proto3" json:"policy,omitempty"`
	// context is the non-secret invocation context. It never carries credential
	// material.
	Context       *InvocationContext `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoke) Reset() {
	*x = Invoke{}
	mi := &file_wso2_cli_module_v1_contract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoke) ProtoMessage() {}

func (x *Invoke) ProtoReflect() protoreflect.Message {
	mi := &file_wso2_cli_module_v1_contract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoke.ProtoReflect.Descriptor instead.
func (*Invoke) Descriptor() ([]byte, []int) {
	return file_wso2_cli_module_v1_contract_proto_rawDescGZIP(), []int{5}
}

func (x *Invoke) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Invoke) GetCommandPath() []string {
	if x != nil {
		return x.CommandPath
	}
	return nil
}

func (x *Invoke) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *Invoke) GetOutputMode() OutputMode {
	if x != nil {
		return x.OutputMode
	}
	return OutputMode_OUTPUT_MODE_UNSPECIFIED
}

func (x *Invoke) GetPolicy() *InvocationPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *Invoke) GetContext() *InvocationContext {
	if x != nil {
		return x.Context
	}
	return nil
}

// InvocationPolicy is the shell policy in force for this invocation.
type InvocationPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// deadline_millis is the time the shell will wait for a terminal message
	// before it closes the protocol stream and terminates the module. Zero means
	// the shell applies its own default.
	DeadlineMillis uint32 `protobuf:"varint,1,opt,name=deadline_millis,json=deadlineMillis,proto3" json:"deadline_millis,omitempty"`
	// interactive reports whether a terminal is attached. The architecture proof
	// never prompts, so a module must not depend on it.
	Interactive   bool `protobuf:"varint,2,opt,name=interactive,proto3" json:"interactive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvocationPolicy) Reset() {
	*x = InvocationPolicy{}
	mi := &file_wso2_cli_module_v1_contract_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationPolicy) ProtoMessage() {}

func (x *InvocationPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_wso2_cli_module_v1_contract_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationPolicy.ProtoReflect.Descriptor instead.
func (*InvocationPolicy) Descriptor() ([]byte, []int) {
	return file_wso2_cli_module_v1_contract_proto_rawDescGZIP(), []int{6}
}

func (x *InvocationPolicy) GetDeadlineMillis() uint32 {
	if x != nil {
		return x.DeadlineMillis
	}
	return 0
}

func (x *InvocationPolicy) GetInteractive() bool {
	if x != nil {
		return x.Interactive
	}
	return false
}

// InvocationContext is the non-secret context the command runs against.
//
// It names the target and identifies the credential arrangement, but it carries
// no credential value and no reference to one. A module obtains access only
// through the shell's authentication broker.
type InvocationContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the selected context's name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// organization_id is the organization the command targets. It is empty until
	// the shell owns a context store.
	OrganizationId string `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InvocationContext) Reset() {
	*x = InvocationContext{}
	mi := &file_wso2_cli_module_v1_contract_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationContext) ProtoMessage() {}

func (x *InvocationContext) ProtoReflect() protoreflect.Message {
	mi := &file_wso2_cli_module_v1_contract_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationContext.ProtoReflect.Descriptor instead.
func (*InvocationContext) Descriptor() ([]byte, []int) {
	return file_wso2_cli_module_v1_contract_proto_rawDescGZIP(), []int{7}
}

func (x *InvocationContext) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InvocationContext) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

// Result is a module's terminal success. The module returns semantic fields and
// the shell alone renders them, so table and JSON output cannot disagree.
type Result struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// schema identifies the semantic shape, such as "reference.status/v1". It
	// lets the shell and downstream tools recognize a result without parsing it.
	Schema string `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	// fields are the result's values in presentation order. The shell renders
	// them in this order in every output mode.
	Fields        []*ResultField `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_wso2_cli_module_v1_contract_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_wso2_cli_module_v1_contract_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_wso2_cli_module_v1_contract_proto_rawDescGZIP(), []int{8}
}

func (x *Result) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *Result) GetFields() []*ResultField {
	if x != nil {
		return x.Fields
	}
	return nil
}

// ResultField is one named value of a result.
type ResultField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the stable machine name, used as the JSON key.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// label is the human-readable column or row label. It falls back to name.
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	// value is the value to display.
	//
	// Every value is a string, so a module formats its own times and numbers.
	// That is a deliberate limit of the architecture proof: it keeps the shell
	// able to render any product's result without knowing anything about it. The
	// cost is that type information is lost at this boundary. Giving values their
	// own types, most likely as a oneof here, is the change to make when a
	// product result needs more than strings.
	Value         string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultField) Reset() {
	*x = ResultField{}
	mi := &file_wso2_cli_module_v1_contract_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultField) ProtoMessage() {}

func (x *ResultField) ProtoReflect() protoreflect.Message {
	mi := &file_wso2_cli_module_v1_contract_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultField.ProtoReflect.Descriptor instead.
func (*ResultField) Descriptor() ([]byte, []int) {
	return file_wso2_cli_module_v1_contract_proto_rawDescGZIP(), []int{9}
}

func (x *ResultField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResultField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ResultField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Problem is a typed, safe-to-render failure. It may travel in either
// direction, and it must never carry credential material: the shell renders
// message and recovery verbatim.
type Problem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// category is the stable failure class, such as "product_service". The shell
	// maps it to an exit class; an unrecognized category is treated as a module
	// process failure rather than a success.
	Category string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	// code is a stable machine-readable identifier such as
	// "reference.status_unavailable".
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// message states what failed, without secret detail.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// recovery states what the user can do next. It may be empty.
	Recovery      string `protobuf:"bytes,4,opt,name=recovery,proto3" json:"recovery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Problem) Reset() {
	*x = Problem{}
	mi := &file_wso2_cli_module_v1_contract_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Problem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Problem) ProtoMessage() {}

func (x *Problem) ProtoReflect() protoreflect.Message {
	mi := &file_wso2_cli_module_v1_contract_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Problem.ProtoReflect.Descriptor instead.
func (*Problem) Descriptor() ([]byte, []int) {
	return file_wso2_cli_module_v1_contract_proto_rawDescGZIP(), []int{10}
}

func (x *Problem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Problem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Problem) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Problem) GetRecovery() string {
	if x != nil {
		return x.Recovery
	}
	return ""
}

var File_wso2_cli_module_v1_contract_proto protoreflect.FileDescriptor

const file_wso2_cli_module_v1_contract_proto_rawDesc = "" +
	"\n" +
	"!wso2/cli/module/v1/contract.proto\x12\x12wso2.cli.module.v1\"\xf2\x02\n" +
	"\bEnvelope\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x121\n" +
	"\x05hello\x18\n" +
	" \x01(\v2\x19.wso2.cli.module.v1.HelloH\x00R\x05hello\x127\n" +
	"\awelcome\x18\v \x01(\v2\x1b.wso2.cli.module.v1.WelcomeH\x00R\awelcome\x124\n" +
	"\x06invoke\x18\f \x01(\v2\x1a.wso2.cli.module.v1.InvokeH\x00R\x06invoke\x124\n" +
	"\x06result\x18\x10 \x01(\v2\x1a.wso2.cli.module.v1.ResultH\x00R\x06result\x127\n" +
	"\aproblem\x18\x11 \x01(\v2\x1b.wso2.cli.module.v1.ProblemH\x00R\aproblemB\t\n" +
	"\amessage\"\xa5\x01\n" +
	"\x05Hello\x12:\n" +
	"\x06module\x18\x01 \x01(\v2\".wso2.cli.module.v1.ModuleIdentityR\x06module\x12+\n" +
	"\x11protocol_versions\x18\x02 \x03(\rR\x10protocolVersions\x123\n" +
	"\x15required_capabilities\x18\x03 \x03(\tR\x14requiredCapabilities\"i\n" +
	"\x0eModuleIdentity\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1f\n" +
	"\vsdk_version\x18\x03 \x01(\tR\n" +
	"sdkVersion\"m\n" +
	"\aWelcome\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x127\n" +
	"\x05shell\x18\x02 \x01(\v2!.wso2.cli.module.v1.ShellIdentityR\x05shell\"E\n" +
	"\rShellIdentity\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\"\xa7\x02\n" +
	"\x06Invoke\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12!\n" +
	"\fcommand_path\x18\x02 \x03(\tR\vcommandPath\x12\x1c\n" +
	"\targuments\x18\x03 \x03(\tR\targuments\x12?\n" +
	"\voutput_mode\x18\x04 \x01(\x0e2\x1e.wso2.cli.module.v1.OutputModeR\n" +
	"outputMode\x12<\n" +
	"\x06policy\x18\x05 \x01(\v2$.wso2.cli.module.v1.InvocationPolicyR\x06policy\x12?\n" +
	"\acontext\x18\x06 \x01(\v2%.wso2.cli.module.v1.InvocationContextR\acontext\"]\n" +
	"\x10InvocationPolicy\x12'\n" +
	"\x0fdeadline_millis\x18\x01 \x01(\rR\x0edeadlineMillis\x12 \n" +
	"\vinteractive\x18\x02 \x01(\bR\vinteractive\"P\n" +
	"\x11InvocationContext\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\"Y\n" +
	"\x06Result\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x127\n" +
	"\x06fields\x18\x02 \x03(\v2\x1f.wso2.cli.module.v1.ResultFieldR\x06fields\"M\n" +
	"\vResultField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"o\n" +
	"\aProblem\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1a\n" +
	"\brecovery\x18\x04 \x01(\tR\brecovery*V\n" +
	"\n" +
	"OutputMode\x12\x1b\n" +
	"\x17OUTPUT_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11OUTPUT_MODE_TABLE\x10\x01\x12\x14\n" +
	"\x10OUTPUT_MODE_JSON\x10\x02B=Z;github.com/wso2/wso2-cli/sdk/protocol/contractv1;contractv1b\x06proto3"

var (
	file_wso2_cli_module_v1_contract_proto_rawDescOnce sync.Once
	file_wso2_cli_module_v1_contract_proto_rawDescData []byte
)

func file_wso2_cli_module_v1_contract_proto_rawDescGZIP() []byte {
	file_wso2_cli_module_v1_contract_proto_rawDescOnce.Do(func() {
		file_wso2_cli_module_v1_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wso2_cli_module_v1_contract_proto_rawDesc), len(file_wso2_cli_module_v1_contract_proto_rawDesc)))
	})
	return file_wso2_cli_module_v1_contract_proto_rawDescData
}

var file_wso2_cli_module_v1_contract_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wso2_cli_module_v1_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_wso2_cli_module_v1_contract_proto_goTypes = []any{
	(OutputMode)(0),           // 0: wso2.cli.module.v1.OutputMode
	(*Envelope)(nil),          // 1: wso2.cli.module.v1.Envelope
	(*Hello)(nil),             // 2: wso2.cli.module.v1.Hello
	(*ModuleIdentity)(nil),    // 3: wso2.cli.module.v1.ModuleIdentity
	(*Welcome)(nil),           // 4: wso2.cli.module.v1.Welcome
	(*ShellIdentity)(nil),     // 5: wso2.cli.module.v1.ShellIdentity
	(*Invoke)(nil),            // 6: wso2.cli.module.v1.Invoke
	(*InvocationPolicy)(nil),  // 7: wso2.cli.module.v1.InvocationPolicy
	(*InvocationContext)(nil), // 8: wso2.cli.module.v1.InvocationContext
	(*Result)(nil),            // 9: wso2.cli.module.v1.Result
	(*ResultField)(nil),       // 10: wso2.cli.module.v1.ResultField
	(*Problem)(nil),           // 11: wso2.cli.module.v1.Problem
}
var file_wso2_cli_module_v1_contract_proto_depIdxs = []int32{
	2,  // 0: wso2.cli.module.v1.Envelope.hello:type_name -> wso2.cli.module.v1.Hello
	4,  // 1: wso2.cli.module.v1.Envelope.welcome:type_name -> wso2.cli.module.v1.Welcome
	6,  // 2: wso2.cli.module.v1.Envelope.invoke:type_name -> wso2.cli.module.v1.Invoke
	9,  // 3: wso2.cli.module.v1.Envelope.result:type_name -> wso2.cli.module.v1.Result
	11, // 4: wso2.cli.module.v1.Envelope.problem:type_name -> wso2.cli.module.v1.Problem
	3,  // 5: wso2.cli.module.v1.Hello.module:type_name -> wso2.cli.module.v1.ModuleIdentity
	5,  // 6: wso2.cli.module.v1.Welcome.shell:type_name -> wso2.cli.module.v1.ShellIdentity
	0,  // 7: wso2.cli.module.v1.Invoke.output_mode:type_name -> wso2.cli.module.v1.OutputMode
	7,  // 8: wso2.cli.module.v1.Invoke.policy:type_name -> wso2.cli.module.v1.InvocationPolicy
	8,  // 9: wso2.cli.module.v1.Invoke.context:type_name -> wso2.cli.module.v1.InvocationContext
	10, // 10: wso2.cli.module.v1.Result.fields:type_name -> wso2.cli.module.v1.ResultField
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_wso2_cli_module_v1_contract_proto_init() }
func file_wso2_cli_module_v1_contract_proto_init() {
	if File_wso2_cli_module_v1_contract_proto != nil {
		return
	}
	file_wso2_cli_module_v1_contract_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Hello)(nil),
		(*Envelope_Welcome)(nil),
		(*Envelope_Invoke)(nil),
		(*Envelope_Result)(nil),
		(*Envelope_Problem)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wso2_cli_module_v1_contract_proto_rawDesc), len(file_wso2_cli_module_v1_contract_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wso2_cli_module_v1_contract_proto_goTypes,
		DependencyIndexes: file_wso2_cli_module_v1_contract_proto_depIdxs,
		EnumInfos:         file_wso2_cli_module_v1_contract_proto_enumTypes,
		MessageInfos:      file_wso2_cli_module_v1_contract_proto_msgTypes,
	}.Build()
	File_wso2_cli_module_v1_contract_proto = out.File
	file_wso2_cli_module_v1_contract_proto_goTypes = nil
	file_wso2_cli_module_v1_contract_proto_depIdxs = nil
}
